# Rust formatter configuration
edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
# Note: imports_granularity and group_imports require nightly
# Uncomment if using rustfmt nightly:
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"
